### PR TITLE
Feature/34 user authentication

### LINKED ISSUE #34: User authentication

### PR DESCRIPTION
**Pull request by lraivio**
This PR:
- Adds auth module to server that can be used in express to handle authentication.
- Adds auth module to app than can be used for authentication state handling.
- Refactors express server related code.
- Adds login and logout links to navbar.

Cannot be tested inside a review app. To test this locally required environment variables need to be added.

Closes #34.

### CODE REVIEW

**Comment by FelixLoether** [comment]
> To test this locally required environment variables need to be added.

Where could I get those?

**Comment by lraivio** [comment]
Added a separate issue to make authentication work in production: #48.

**Comment by lraivio** [comment]
Ideas for better auth endpoint and action naming is welcome. For example `/auth` is now used for getting authentication state from express and the api action for getting this is now called `fetchAuthState`.

**Comment by FelixLoether** [comment]
I think the current naming is OK. You can rebase onto develop + merge.

**Pull request merged**
