### PR TITLE
Basic timeline components

### PR DESCRIPTION
**Pull request by FelixLoether**
The basic components for #9.

I'll make a separate PR for the styles and some extra functionality so the review of this can already be started.

To test this locally, you can run the command `patch -p1 < test-timeline.patch` after saving this as `test-timeline.patch`:

```patch
diff --git a/app/api/reducers/dataReducer.js b/app/api/reducers/dataReducer.js
index 421141e..c5c4917 100644
--- a/app/api/reducers/dataReducer.js
+++ b/app/api/reducers/dataReducer.js
@@ -4,7 +4,33 @@ import immutable from 'seamless-immutable';
 import actionTypes from '../actionTypes';

 const initialState = immutable({
-  resources: {},
+  resources: {
+    '0123456789abcdef': {
+      id: '0123456789abcdef',
+      name: { fi: 'Testiresurssi' },
+      peopleCapacity: 7,
+      reservations: [
+        {
+          begin: '2016-01-01T12:00:00+02:00',
+          end: '2016-01-01T14:00:00+02:00',
+          id: '21346',
+          name: 'Haastattelut',
+        },
+        {
+          begin: '2016-01-01T14:30:00+02:00',
+          end: '2016-01-01T15:00:00+02:00',
+          id: '21348',
+          name: 'Tapsu',
+        },
+        {
+          begin: '2016-01-02T12:00:00+02:00',
+          end: '2016-01-02T14:00:00+02:00',
+          id: '21349',
+          name: 'Paha',
+        },
+      ],
+    },
+  },
   units: {},
 });

diff --git a/app/pages/search/SearchContainer.js b/app/pages/search/SearchContainer.js
index 259cb2e..1e77e86 100644
--- a/app/pages/search/SearchContainer.js
+++ b/app/pages/search/SearchContainer.js
@@ -1,9 +1,11 @@
+import moment from 'moment';
 import React, { Component, PropTypes } from 'react';
 import Loader from 'react-loader';
 import { connect } from 'react-redux';
 import { Link } from 'react-router';

 import { fetchResources } from 'api/actions';
+import AvailabilityView from 'shared/availability-view';
 import selector from './searchSelector';

 function renderResource(resource) {
@@ -16,6 +18,10 @@ function renderResource(resource) {
   );
 }

+function onDateChange(newValue) {
+  console.log('new', newValue.format());
+}
+
 export class UnconnectedSearchContainer extends Component {
   componentDidMount() {
     this.props.fetchResources();
@@ -26,6 +32,14 @@ export class UnconnectedSearchContainer extends Component {

     return (
       <div className="search">
+        <AvailabilityView
+          date={moment('2016-01-01')}
+          groups={[
+            { name: 'Aleksanterinkatu 20', resources: ['0123456789abcdef'] },
+            { name: 'Matinkatu 21', resources: ['0123456789abcdef'] },
+          ]}
+          onDateChange={onDateChange}
+        />
         <h1>Tilat</h1>
         <Loader loaded={!isFetching}>
           <ul>
```
That test code adds the resource availability thing to the search page with some test data.

### CODE REVIEW

**Comment by lraivio** [comment]
I was thinking about Component naming.

```
ResourceAvailability -> AvailabilityView || DayAvailability
  Sidebar
    GroupInfo
      ResourceInfo
  GroupedTimeline -> TimelineGroups
    GroupTimeline -> TimelineGroup
      ResourceReservationsTimelineContainer -> AvailabilityTimelineContainer
        ReservationsTimeline -> AvailabilityTimeline
```

- [ ] Just suggestions. What do you think?

**Comment by lraivio** [comment]
- [ ] The resource-availability folder has quite a lot of files. Maybe components that belong to sidebar and components that belong to the main view could be put into their own folders to make finding files easier.

**Comment by FelixLoether** [comment]
Changes made.

**Comment by lraivio** [comment]
- [ ] Looks good 👍 You can squash the fixups.

**Pull request closed without merging**
